# Generated by Django 4.2.3 on 2023-07-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_dealsdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='schedule_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='schedule_time',
            new_name='time',
        ),
    ]
