# Generated by Django 4.2.3 on 2023-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_schedule_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
