# Generated by Django 4.2.3 on 2023-07-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_appointment_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
