# Generated by Django 4.2.3 on 2023-07-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_doctor_contact_alter_doctor_entered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
