# Generated by Django 4.2.3 on 2023-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_doctor_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entered_by',
            field=models.CharField(max_length=100),
        ),
    ]
