# Generated by Django 4.2.3 on 2023-07-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
