# Generated by Django 4.2.3 on 2023-07-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_product_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='quantity_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
