# Generated by Django 4.2.3 on 2023-07-22 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_dealsdetail_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='quantity_ordered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
