# Generated by Django 4.2.3 on 2023-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_dealsdetail_quantity_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='quantity_ordered',
            field=models.PositiveIntegerField(),
        ),
    ]
