# Generated by Django 4.2.3 on 2023-07-27 11:56

import datetime
from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[employee.models]),
        ),
    ]
