# Generated by Django 4.2.3 on 2023-07-27 11:59

import datetime
from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 11, 59, 39, 470470, tzinfo=datetime.timezone.utc), validators=[employee.models]),
        ),
    ]
