# Generated by Django 4.2.3 on 2023-07-31 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_appointment_date_alter_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999, message='Contact number too large.'), django.core.validators.MinValueValidator(1000000000, message='Contact number too small.')]),
        ),
    ]
