# Generated by Django 4.2.3 on 2023-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_alter_doctor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='quantity_ordered',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
